Use `drop_operation_state` to avoid stack overflows
eth-cscs/DLA-Future pull request #1004
Opened 2023-10-06 13:47 UTC by aurianer

Will need the pika 0.19.1 patch release (it will probably be released next week), in the meantime I'm temporarily using pika@main in CI
Attempt to fix #1005. Fixes #665.

2023-10-09 05:40 UTC, msimberg commented
cscs-ci run

2023-10-10 09:45 UTC, rasolca reviewed
This PR still depend on `pika@main`. I think it should be updated to `pika@0.19.1` before considering it ready.

2023-10-10 09:45 UTC, rasolca commented on CMakeLists.txt
> +find_package(pika REQUIRED)
Please add version constrain back.

2023-10-10 09:45 UTC, rasolca commented on spack/packages/dla-future/package.py
> +    depends_on("pika@main", when="@master")
still depend on `@main`

2023-10-10 11:51 UTC, msimberg reviewed
Before approving I'd like to hear if you were able to reproduce the bug locally and if the previously failing tests have been run enough times in CI? It was after all the `band_to_tridiag` miniapp that was failing that revealed the stack overflows, and now it was the C API eigensolver tests...

2023-10-10 11:52 UTC, msimberg commented on include/dlaf/sender/transform.h
>  #if defined(DLAF_WITH_GPU)
I'd also like to see `drop_operation_state` used in the GPU branch(es) below.

2023-10-10 12:13 UTC, msimberg requested changes
This also needs a bump to the spack commit. It's currently installing `pika@main`.

2023-12-12 15:23 UTC, msimberg commented
cscs-ci run

2023-12-12 16:28 UTC, merged