Making arguments "const" in Lapack and Blas wrappers
eth-cscs/DLA-Future pull request #276
Opened 2020-10-19 16:39 UTC by Sely85

Added `const` declaration to Lapack and Blas functions arguments (`blas::Uplo`, `blas::Side`, ...) to avoid erroneous modifications.

2020-11-03 08:49 UTC, albestro approved these changes
LGTM

2020-11-04 16:32 UTC, rasolca reviewed
There is a conflict and don't know if new files from #261 have been already fixed.

2020-11-04 16:47 UTC, Sely85 commented
> There is a conflict and don't know if new files from #261 have been already fixed.

Yep, files from #261 have been fixed (if introduced in that PR for the first time).

2020-11-05 11:05 UTC, rasolca requested changes

2020-11-05 11:05 UTC, rasolca commented on test/include/dlaf_test/matrix/util_generic_blas.h
> +                              : false;
No need to use ternary operator here. Just assign the boolean value.
```suggestion
  const bool op_a_lower = (uplo == blas::Uplo::Lower && op == blas::Op::NoTrans) ||
                          (uplo == blas::Uplo::Upper && op != blas::Op::NoTrans);
```

2020-11-05 11:05 UTC, rasolca commented on test/include/dlaf_test/matrix/util_generic_blas.h
> +                              : false;
See above.
```suggestion
  const bool op_a_lower = (uplo == blas::Uplo::Lower && op == blas::Op::NoTrans) ||
                          (uplo == blas::Uplo::Upper && op != blas::Op::NoTrans);
```

2020-11-05 11:05 UTC, teonnik approved these changes

2020-11-05 12:05 UTC, rasolca commented
bors try

2020-11-05 12:06 UTC, rasolca approved these changes

2020-11-05 12:38 UTC, merged