Remove duplicated operator<<
eth-cscs/DLA-Future pull request #282
Opened 2020-10-27 16:52 UTC by rasolca

Closes #281.

2020-10-27 16:52 UTC, rasolca commented
bors try

2020-10-28 07:49 UTC, Sely85 requested changes

2020-10-28 07:49 UTC, Sely85 commented on include/dlaf/blas/enum_output.h
> +  }
should we add a `break;` in this `case` as well?

```suggestion
  break;
  }
```

2020-10-28 10:45 UTC, teonnik approved these changes

2020-10-28 20:03 UTC, Sely85 approved these changes
Looks good!

2020-10-29 07:31 UTC, albestro commented
LGTM too!

Just one question: I quickly run grep over the repo and there are few locations where we are using `blaspp` provided one. Wouldn't it be a nice chance to migrate them?

```
include/dlaf/auxiliary/norm/mc.tpp:      DLAF_ASSERT(false, "not yet implemented", lapack::norm2str(norm_type));
include/dlaf/auxiliary/norm/mc.tpp:          DLAF_ASSERT(false, "not yet implemented", lapack::norm2str(norm_type), blas::uplo2str(uplo));
test/unit/auxiliary/mc/test_norm.cpp:  SCOPED_TRACE(::testing::Message() << "norm=" << lapack::norm2str(norm_type)
test/unit/auxiliary/mc/test_norm.cpp:                                    << " uplo=" << blas::uplo2str(uplo) << " changed element=" << index
test/unit/test_lapack_tile/test_lange.h:  SCOPED_TRACE(::testing::Message() << "LANGE: " << lapack::norm2str(norm) << ", " << a.size()
test/unit/test_lapack_tile/test_lange.h:      FAIL() << "norm " << lapack::norm2str(norm) << " is not supported by lange";
test/unit/test_lapack_tile/test_lantr.h:  SCOPED_TRACE(::testing::Message() << "LANTR: " << lapack::norm2str(norm) << ", " << a.size()
test/unit/test_lapack_tile/test_lantr.h:                                    << ", ld = " << a.ld() << " uplo = " << blas::uplo2str(uplo)
test/unit/test_lapack_tile/test_lantr.h:                                    << " diag = " << blas::diag2str(diag));
test/unit/test_lapack_tile/test_lantr.h:      FAIL() << "norm " << lapack::norm2str(norm) << " is not supported by lantr";
```

2020-10-29 07:32 UTC, albestro approved these changes
LGTM too!

Just one question: I quickly run grep over the repo and there are few locations where we are using `blaspp` provided one. Wouldn't it be a nice chance to migrate them?

```
include/dlaf/auxiliary/norm/mc.tpp:      DLAF_ASSERT(false, "not yet implemented", lapack::norm2str(norm_type));
include/dlaf/auxiliary/norm/mc.tpp:          DLAF_ASSERT(false, "not yet implemented", lapack::norm2str(norm_type), blas::uplo2str(uplo));
test/unit/auxiliary/mc/test_norm.cpp:  SCOPED_TRACE(::testing::Message() << "norm=" << lapack::norm2str(norm_type)
test/unit/auxiliary/mc/test_norm.cpp:                                    << " uplo=" << blas::uplo2str(uplo) << " changed element=" << index
test/unit/test_lapack_tile/test_lange.h:  SCOPED_TRACE(::testing::Message() << "LANGE: " << lapack::norm2str(norm) << ", " << a.size()
test/unit/test_lapack_tile/test_lange.h:      FAIL() << "norm " << lapack::norm2str(norm) << " is not supported by lange";
test/unit/test_lapack_tile/test_lantr.h:  SCOPED_TRACE(::testing::Message() << "LANTR: " << lapack::norm2str(norm) << ", " << a.size()
test/unit/test_lapack_tile/test_lantr.h:                                    << ", ld = " << a.ld() << " uplo = " << blas::uplo2str(uplo)
test/unit/test_lapack_tile/test_lantr.h:                                    << " diag = " << blas::diag2str(diag));
test/unit/test_lapack_tile/test_lantr.h:      FAIL() << "norm " << lapack::norm2str(norm) << " is not supported by lantr";
```

2020-10-29 09:47 UTC, rasolca commented
bors try

2020-10-29 10:00 UTC, albestro commented
bors try

In local I had an old version of lapackpp, now the header has been moved, it should be ok now

2020-10-29 10:16 UTC, rasolca commented
bors try
Something external failed.

2020-10-29 14:47 UTC, rasolca commented
bors try

2020-10-29 15:09 UTC, albestro approved these changes

2020-10-29 15:10 UTC, albestro commented
I was viewing changes after the merge, but I didn't touch anything, but it seems there was a pending review (not sure, no messages, no comments, just files marked as view).

Anyway, it seems the maintenance is still ongoing, we may have to wait.

2020-10-29 18:13 UTC, rasolca commented
bors try

2020-11-02 10:08 UTC, rasolca commented
bors try

2020-11-02 11:20 UTC, merged