first proposal according #236
eth-cscs/DLA-Future pull request #290
Opened 2020-11-09 15:14 UTC by rasolca

I refactored Cholesky according to Mikael suggestion.

new API (which dispatches to internal API):
```
dlaf::factorization::cholesky<backend, device, Type>(...)
```
new internal API:
```
template <Backend b, Device d, class T>
Cholesky{};

template <class T>
Cholesky<MC, CPU, T>{
// Note that call_L cannot be defined here, otherwise ETI doesn't work. 
static void call_L(..);
};
// non inline definition needed by ETI
template <class T>
void Cholesky<MC, CPU, T>::call_L(..){
  ..
}
```

The new directory structure is the following:
```
factorization/
    cholesky.h  <-  user API (template functions that dispatch to internal API)
    cholesky/
         cholesky.h  <-  internal template struct declaration
         cholesky_mc.h  <-  template partial specialization for MC backend
    # other algorithms e.g. QR
    qr.h
    qr/
         qr.h
         qr_mc.h
         t_factor.h
         t_factor_mc.h
```
 
@albestro @teonnik @msimberg What do you think?

2020-11-10 10:47 UTC, teonnik commented
I like where this is heading. A few points of discussion:

The `cholesky/` contains the implementation details of the API. Can we rename things a little bit, for example:

`cholesky/cholesky.h` -> `cholesky/api.h` (i.e. the internal API of cholesky)
`cholesky/cholesky_mc.h` -> `cholesky/mc.h` (to avoid name repetitions)

2020-11-11 10:23 UTC, teonnik requested changes

2020-11-11 10:23 UTC, teonnik commented on include/dlaf/factorization/cholesky/mc.h
> +};
Do we need the `Device device` template parameter here? It doesn't seem to be used in `call_L()`. Perhaps we can just set it to `Device::CPU` and remove it from `template<...>`

2020-11-13 07:13 UTC, teonnik commented on include/dlaf/factorization/factorization.h
> +#include "dlaf/factorization/cholesky.h"
This header should probably replace the `factorization.h` header outside of the `factorization/` directory. That header has a wrong include statement in it (dlaf/factorization/mc.h), this one has the right include statement.

2020-11-13 10:13 UTC, teonnik approved these changes

2020-11-13 11:59 UTC, rasolca commented
bors try

2020-11-13 12:49 UTC, albestro approved these changes
Very good job!

Just a technical question: is there any benefit of using empty structs instead of just declaring them? See my comment just for reference in the code.

2020-11-13 12:49 UTC, albestro commented on include/dlaf/auxiliary/norm/api.h
> +struct Norm {};
like this.

2020-11-13 14:53 UTC, merged