mpi race condition
eth-cscs/DLA-Future pull request #362
Opened 2021-04-23 15:18 UTC by rasolca

Tile lifetime for future is not guaranteed, while for shared_future it is.

2021-04-23 15:18 UTC, rasolca commented
bors try

2021-04-23 15:41 UTC, rasolca commented
bors try

2021-04-23 16:05 UTC, msimberg commented
Is this exactly about the issue we've been discussing in the last few meetings, i.e. the MPI executor does not keep the tiles alive for the duration of the communication? If yes, could you give unwrapExtendTiles a try? You may need the updated one from the #319.

2021-04-23 16:07 UTC, rasolca commented
Yes exactly. What puzzles me is the fact that shared futures work correctly.

2021-04-27 09:07 UTC, msimberg commented
I'll admit the reason for the difference between `future` and `shared_future` was a bit surprising to me. The reason is not 100% due to the futures themselves. The reason the test fails with `future` is that `get`ting the tile from the future invalidates the future, and so the tile goes out of scope at the end of the `sendBcast` function. With the `shared_future` `get` only gets a `const&` to the tile. However, what I was expecting to happen is that the tuple that gets passed to `invoke_fused` in https://github.com/eth-cscs/DLA-Future/blob/48d39ac023fc2e5abf22e3b8da8e574b932b21ed/include/dlaf/communication/executor.h#L141 would go out of scope at the latest at the end of the `invoke_fused_wrapper` constructor. However, it doesn't, and the tuple instead goes out of scope at the end of the lambda scope at https://github.com/eth-cscs/DLA-Future/blob/48d39ac023fc2e5abf22e3b8da8e574b932b21ed/include/dlaf/communication/executor.h#L144, i.e. after the request has been handled and so the tile lives long enough. A little godbolt example to show what happens: https://godbolt.org/z/rv89nsczq.

TL;DR: `invoke_fused` takes the tuple by rvalue reference but never moves it internally. `unwrapping` only invalidates `future` because it has no other choice when calling `get`. This doesn't happen with `shared_future`. As a result the tuple passed to `invoke_fused` lives until the end of the scope where it's created.

2021-04-27 09:13 UTC, msimberg requested changes
https://github.com/eth-cscs/DLA-Future/blob/48d39ac023fc2e5abf22e3b8da8e574b932b21ed/include/dlaf/communication/executor.h#L122 and https://github.com/eth-cscs/DLA-Future/blob/48d39ac023fc2e5abf22e3b8da8e574b932b21ed/include/dlaf/communication/executor.h#L140 also need to change to at least move the `all_args` tuple.

2021-04-27 09:13 UTC, msimberg commented on test/unit/communication/test_comm_matrix.cpp
> +    hpx::dataflow(ex, hpx::util::unwrapping(comm::sendBcast<double>), mat(index), ccomm());
```suggestion
    hpx::dataflow(ex, dlaf::matrix::unwrapExtendTiles(comm::sendBcast<double>), mat(index), ccomm());
```

2021-04-27 09:13 UTC, msimberg commented on test/unit/communication/test_comm_matrix.cpp
> +    hpx::dataflow(ex, hpx::util::unwrapping(comm::sendBcast<double>), mat.read(index), ccomm());
```suggestion
    hpx::dataflow(ex, dlaf::matrix::unwrapExtendTiles(comm::sendBcast<double>), mat.read(index), ccomm());
```

2021-04-27 11:59 UTC, msimberg commented on test/unit/communication/test_comm_matrix.cpp
> +#include <hpx/futures/future.hpp>
```suggestion
#include <hpx/local/future.hpp>
```

2021-04-28 11:30 UTC, rasolca commented
bors try

2021-04-28 11:57 UTC, rasolca commented
bors try
Hoping that the strange failure of the CI doesn't happen again...

2021-05-11 09:41 UTC, rasolca commented
bors try

2021-05-11 11:49 UTC, msimberg approved these changes

2021-05-11 11:52 UTC, merged