Moving to C++17 standard
eth-cscs/DLA-Future pull request #434
Opened 2021-12-06 10:36 UTC by Sely85

Simplifying the code with C++17 standard features: 
- structured bindings: substitute `std::tie` with `auto`,
- inline variables: using `_v` for std::traits and writing DLAF custom helper templates

2021-12-10 16:26 UTC, msimberg commented
Just FYI, we have an issue for HPX for tracking C++17 "modernizations": https://github.com/STEllAR-GROUP/hpx/issues/5497. We're doing those in small steps, and I wouldn't suggest doing it all in this PR, but it may give some additional ideas on what to in other PRs.

2021-12-13 09:31 UTC, rasolca reviewed
When you loop over the configs vectors, please make sure to either take a const reference, or, in case the values should be modified to copy them.

2021-12-13 09:31 UTC, rasolca commented on test/unit/factorization/mc/test_compute_t_factor.cpp
> +  for (auto& [a_m, a_n, mb, nb, k, v_start] : configs) {
This can lead to a change in the configs vector.
If the parameter can be modified, please copy them, otherwise take a const reference.

2021-12-13 09:31 UTC, rasolca commented on test/unit/factorization/mc/test_compute_t_factor.cpp
> +    for (auto& [a_m, a_n, mb, nb, k, v_start] : configs) {
Same as before. Either copy or const reference.

2021-12-13 12:45 UTC, rasolca commented
I added a fix, as structured binding are not capturable by lambdas. (gcc compiles anyway, but clang doesn't)

2021-12-14 11:39 UTC, rasolca approved these changes

2021-12-14 11:39 UTC, rasolca commented
bors try

2021-12-14 12:39 UTC, rasolca requested changes

2021-12-14 12:39 UTC, rasolca commented on include/dlaf/cublas/executor.h
> +  std::enable_if_t<internal::isAsyncCublasCallable_v,
Missing template

2021-12-14 12:39 UTC, rasolca commented on include/dlaf/cusolver/executor.h
> +  std::enable_if_t<internal::isAsyncCusolverCallable_v,
Missing template

2021-12-14 14:25 UTC, rasolca commented
bors try

2021-12-14 15:55 UTC, rasolca commented
bors try

2021-12-14 17:05 UTC, rasolca commented on test/unit/test_lapack_tile.cpp
> +      for (const auto& [m, extra_lda, extra_ldb] : _sizes) {
```suggestion
      for (const auto& [m, extra_lda, extra_ldb] : hegst_sizes) {
```

2021-12-15 09:22 UTC, rasolca commented
bors try

2021-12-15 11:50 UTC, rasolca approved these changes

2021-12-15 11:52 UTC, merged