Distributed version of triangular solver
eth-cscs/DLA-Future pull request #518
Opened 2022-04-01 17:50 UTC by Sely85

This PR includes code for missing distributed transposed cases (namely LUT, RLT, and RUT) of the triangular solver algorithm.
These cases have been developed following LLT approach.

2022-04-04 08:32 UTC, albestro requested changes
Some minor comments, which are more generally applicable also to other parts of the changes in this PR.

2022-04-04 08:32 UTC, albestro commented on include/dlaf/solver/triangular/impl.h
> +                                 LocalTileIndex{bt_offset.row(), distr_b.localNrTiles().cols()}))
Since the start index is hard-coded to be the origin, you can use the helper `iterate_range2d` that accepts just the end index.

2022-05-18 09:52 UTC, rasolca approved these changes

2022-05-18 12:20 UTC, albestro requested changes

2022-05-18 12:23 UTC, rasolca commented on include/dlaf/solver/triangular/impl.h
> +      a_panel.setHeight(mat_a.tileSize(kk).cols());
```suggestion
      a_panel.setHeight(mat_a.tileSize(kk).rows());
```

2022-05-18 12:23 UTC, rasolca commented on include/dlaf/solver/triangular/impl.h
> +      a_panel.setHeight(mat_a.tileSize(kk).cols());
```suggestion
      a_panel.setHeight(mat_a.tileSize(kk).rows());
```

2022-05-18 12:23 UTC, rasolca commented on include/dlaf/solver/triangular/impl.h
> +      b_panel.setHeight(mat_a.tileSize(kk).cols());
the same applies for line 570-571 as well. (both should be cols)

2022-05-30 08:47 UTC, rasolca commented
bors try

2022-06-01 12:34 UTC, merged