Introduce gemm (local)
eth-cscs/DLA-Future pull request #541
Opened 2022-05-02 09:08 UTC by albestro

This PR has its root in a very small part of the work going on in #436, where a constrained use-case of a `gemm` is used.

The specific use-case is a gemm between sub-matrices, which have the characteristic of being placed in the same exact spot in all matrices, so both inputs and output.
For this reason, given a linear range `[s, e]`, the operations is `C[s:e, s:e] = beta * C[s:e, s:e] + alpha * A[s:e, s:e] * B[s:e, s:e]`.
In particular, elements outside these 2D ranges are not referenced/modified in any of the matrices involved.

It is a specific use-case but, as soon as we will change Matrix API to manage sub-matrix not as a special case, it will become a normal `gemm`. In the meanwhile, I think we can go a bit more "easier" on its API.

Looking forward to suggestions/feedbacks.

2022-05-03 07:00 UTC, teonnik requested changes
LGTM, some minor changes needed!

2022-05-03 07:00 UTC, teonnik commented on test/include/dlaf_test/matrix/util_generic_blas.h
> +  auto elC = [a, b](const GlobalElementIndex) { return TypeUtilities<T>::polar(0, 0); };
`a` and `b` are not used in the lambda, warnings are generated.

2022-05-03 12:26 UTC, rasolca commented on include/dlaf/multiplication/general/impl.h
> +void GeneralSub<D, T>::call(const SizeType a, const SizeType b, const blas::Op opA, const blas::Op opB,
Missing `NN` in the name of the function...

2022-05-16 14:09 UTC, albestro commented
bors try

2022-05-17 07:39 UTC, teonnik approved these changes

2022-05-17 08:09 UTC, msimberg approved these changes
No comments.

2022-05-17 08:28 UTC, rasolca approved these changes

2022-05-17 08:28 UTC, merged