minor: use `pika::scoped_finalizer` in miniapps
eth-cscs/DLA-Future pull request #566
Opened 2022-06-09 14:06 UTC by albestro

Follow up https://github.com/eth-cscs/DLA-Future/pull/561#discussion_r890892362

- Use `pika::scoped_finalizer`
- Minor fix: names in some miniapps help messages

2022-06-09 14:48 UTC, msimberg requested changes

2022-06-09 14:48 UTC, msimberg commented on miniapp/miniapp_band_to_tridiag.cpp
> +#include <pika/init_runtime/scoped_finalize.hpp>
```suggestion
```
and the same in the other miniapps of course.

We added the very minimum of documentation in 0.5.0: https://github.com/pika-org/pika#documentation :sweat_smile: I know there's a long way to go...

2022-06-09 15:11 UTC, msimberg commented on miniapp/miniapp_band_to_tridiag.cpp
> +#include <pika/init_runtime/scoped_finalize.hpp>
Yep: https://github.com/pika-org/pika/blob/977f4533ccb9f773af004e9f58b7802d250b4b70/libs/pika/init_runtime/include/pika/init.hpp#L10.

2022-06-13 07:47 UTC, msimberg approved these changes

2022-06-13 11:19 UTC, rasolca commented
bors try

2022-06-13 11:42 UTC, rasolca approved these changes

2022-06-14 16:56 UTC, merged