Make `miniapp` an indep
eth-cscs/DLA-Future pull request #764
Opened 2023-01-09 09:32 UTC by albestro

2023-01-13 08:33 UTC, msimberg requested changes
Looks good to me.

Do I understand correctly that you (or someone) is planning on separately adding the CI job that then tests that `find_package(DLAF)` works correctly?

2023-01-13 08:33 UTC, msimberg commented on miniapp/CMakeLists.txt
> +project(dlaf-miniapps)
```suggestion
project(DLAF-miniapps)
```
maybe? Just to keep the all-caps of `DLAF` for the main project.

2023-01-13 10:52 UTC, rasolca approved these changes

2023-01-13 13:04 UTC, albestro commented
cscs-ci run

2023-01-16 08:50 UTC, msimberg approved these changes

2023-01-16 10:38 UTC, merged