Fix `tridiag_rank1_barrier_busy_wait` configuration option
eth-cscs/DLA-Future pull request #907
Opened 2023-06-14 13:06 UTC by msimberg

It was initialized with the wrong value. Sorry about this.

I will separately rerun the benchmarks that I did for the tridiagonal solver, but now I can include the distributed results as well (with #904).

2023-06-14 13:06 UTC, msimberg commented
cscs-ci run

2023-06-14 13:07 UTC, msimberg commented
cscs-ci run

2023-06-14 13:08 UTC, albestro commented
As soon as this one gets merged I'm going to rebase #904 and introduce `tridiag_rank1_barrier_busy_wait` parameter also in the distributed 😉

2023-06-14 14:27 UTC, albestro requested changes

2023-06-14 14:27 UTC, albestro commented on src/init.cpp
> +  updateConfigurationValue(vm, param.tridiag_rank_barrier_busy_wait_us,
```suggestion
  updateConfigurationValue(vm, param.tridiag_rank1_barrier_busy_wait_us,
```

2023-06-14 14:42 UTC, msimberg commented
cscs-ci run

2023-06-15 16:16 UTC, msimberg commented
cscs-ci run

2023-06-15 18:53 UTC, albestro approved these changes

2023-06-16 13:14 UTC, rasolca approved these changes

2023-06-16 13:17 UTC, merged