Ensure umpire~cuda~rocm is used when ~cuda~rocm
eth-cscs/DLA-Future pull request #931
Opened 2023-07-11 09:41 UTC by RMeli

Ensure `umpire~cuda~rocm` is used when `~cuda~rocm`.

Related to https://github.com/LLNL/Umpire/pull/827.

2023-07-11 11:28 UTC, RMeli commented on spack/packages/dla-future/package.py
> +    depends_on("umpire~examples)
```suggestion
    depends_on("umpire~examples")
```

2023-07-11 12:53 UTC, rasolca requested changes

2023-07-11 15:54 UTC, rasolca approved these changes

2023-07-11 16:09 UTC, rasolca commented
Should be rebased/merged to include the changes of #932.

2023-07-12 07:27 UTC, msimberg approved these changes

2023-07-12 07:58 UTC, msimberg commented
cscs-ci run

2023-07-12 08:48 UTC, merged